"""Initial Migration

Revision ID: 753e27c85f24
Revises: 9c60bee2012e
Create Date: 2018-09-17 13:46:44.960011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753e27c85f24'
down_revision = '9c60bee2012e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribers', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
